apiVersion: v1
kind: Pod
metadata:
  labels:
    run: influx-yaml
  name: influx-yaml
spec:
  containers:
  - image: influxdb:1.8
    name: influx-yaml
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
