apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influx
  name: influx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: influx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
      - image: influxdb:1.8
        name: influxdb
        resources: {}
status: {}
